sudo: true
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ['g++-5']
      env:
        - MATRIX_EVAL="CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX=g++-7 && COVERAGE=1"
      after_success:
        - pip install --user cpp-coveralls
        - coveralls -r . -i DonerSerializer/include/donerserializer --gcov-options "\-lp"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CXX=clang++-3.9"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew upgrade cmake && CXX=clang++"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && brew upgrade cmake && CXX=g++"

script: ./scripts/travis.sh
